### ISSUE TITLE
Error: EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by vunb** [vunb/vntk#16]
Install dependency [vunb/node-crfsuite](https://github.com/vunb/node-crfsuite) got following error:

```npm
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "crfsuite" "--save"
npm ERR! node v6.9.0
npm ERR! npm  v4.0.0
npm ERR! path D:\node\github\vntk\vntk\node_modules\crfsuite
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'D:\node\github\vntk\vntk\node_modules\crfsuite' -> 'D:\node\github\vntk\vntk\node_modules\.crfsuite.DELETE'
npm ERR!     at moveAway (C:\Users\nhuba\AppData\Roaming\nvm\v6.9.0\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\nhuba\AppData\Roaming\nvm\v6.9.0\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Users\nhuba\AppData\Roaming\nvm\v6.9.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'D:\node\github\vntk\vntk\node_modules\crfsuite' -> 'D:\node\github\vntk\vntk\node_modules\.crfsuite.DELETE'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'D:\node\github\vntk\vntk\node_modules\crfsuite' -> 'D:\node\github\vntk\vntk\node_modules\.crfsuite.DELETE'
npm ERR!     at moveAway (C:\Users\nhuba\AppData\Roaming\nvm\v6.9.0\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\nhuba\AppData\Roaming\nvm\v6.9.0\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Users\nhuba\AppData\Roaming\nvm\v6.9.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'D:\node\github\vntk\vntk\node_modules\crfsuite' -> 'D:\node\github\vntk\vntk\node_modules\.crfsuite.DELETE'
npm ERR!     at Error (native) parent: 'vntk' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\node\github\vntk\vntk\npm-debug.log
```

**Comment by vunb** [comment]
After upgrade `npm` to `5.5.1`, the error was resolved!

> npm install -g npm

See also: react-community/create-react-native-app#191
