### ISSUE TITLE
Lỗi khi settup server api

### ISSUE THREAD

**Issue by vitconproduction** [vunb/vntk#50]
TypeError: engine is not a function
    at Object.<anonymous> (/Users/TrieuVu/vntk/server/app.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)

Nhờ anh chỉ em fix với nhé !

**Comment by vunb** [comment]
Hi @vitconproduction hiện demo chạy server đang lỗi, mình sẽ fix sớm vấn đề này.

**Comment by vunb** [comment]
Bạn clone code về và chạy lại sample nhé. Cảm ơn bạn đã report issue 👍
